### ISSUE TITLE
sydtest-hedis-0.0.0.0 fails to build with hedis-0.16.1

### ISSUE THREAD

**Issue by juhp** [NorfairKing/sydtest#132]
For stackage nightly:
```
       Building library for sydtest-hedis-0.0.0.0...
       [1 of 2] Compiling Paths_sydtest_hedis
       [2 of 2] Compiling Test.Syd.Redis                          
       /home/curators/work/unpack-dir/unpacked/sydtest-hedis-0.0.0.0-46458338081c861712d4a04f3f7281497dc78f38b64fd598844418f0db76e9f7/src/Test/Syd/Redis.hs:67:44: error: [GHC-22385]                                                                                   
           Not in scope: record field ‘connectPort’
          |                                                       
       67 |   let connInfo = Redis.defaultConnectInfo {connectPort = PortNumber redisServerHandlePort}
          |                                            ^^^^^^^^^^^
```

https://github.com/commercialhaskell/stackage/issues/8017

**Comment by NorfairKing** [comment]
afaict no one uses that package so you can leave it out of stackage as well.
